# Generated by Django 4.1.3 on 2023-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='profiles', verbose_name='عکس کاربر'),
        ),
    ]
