# Generated by Django 4.1.3 on 2023-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دانلود'),
        ),
    ]
